// importing packages
package com.student.project;
// Generated Mar 25, 2016 2:00:16 AM by Hibernate Tools 4.3.1.Final

// importing hibernate utilities
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Classroom generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "classroom", catalog = "student_database")

// classroom method
public class Classroom implements java.io.Serializable {
	
	// declaration of variables
	private int idclassroom;
	private int roomNumber;
	private int floor;
	private int capacity;
	private String department;

	// constructor
	public Classroom() {
	}
	
	// copy constructor initializes the values
	public Classroom(int idclassroom, int roomNumber, int floor, int capacity, String department) {
		this.idclassroom = idclassroom;
		this.roomNumber = roomNumber;
		this.floor = floor;
		this.capacity = capacity;
		this.department = department;
	}

	@Id
	@Column(name = "idclassroom", unique = true, nullable = false)
	// gets classroom id
	public int getIdclassroom() {
		return this.idclassroom;
	}

	// sets classroom id
	public void setIdclassroom(int idclassroom) {
		this.idclassroom = idclassroom;
	}

	// gets room number
	@Column(name = "Room_Number", nullable = false)
	public int getRoomNumber() {
		return this.roomNumber;
	}

	// sets room number
	public void setRoomNumber(int roomNumber) {
		this.roomNumber = roomNumber;
	}
	
	// gets floor number
	@Column(name = "Floor", nullable = false)
	public int getFloor() {
		return this.floor;
	}

	// sets floor number
	public void setFloor(int floor) {
		this.floor = floor;
	}

	// gets classroon capacity
	@Column(name = "Capacity", nullable = false)
	public int getCapacity() {
		return this.capacity;
	}

	// sets classroom capacity
	public void setCapacity(int capacity) {
		this.capacity = capacity;
	}

	// gets department name
	@Column(name = "Department", nullable = false, length = 45)
	public String getDepartment() {
		return this.department;
	}

	// sets department name
	public void setDepartment(String department) {
		this.department = department;
	}

}
