// package name
package com.student.project;
// Generated Mar 25, 2016 2:00:16 AM by Hibernate Tools 4.3.1.Final

// imports java utilities
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Grades generated by hbm2java
 */

// Grades method
@SuppressWarnings("serial")
@Entity
@Table(name = "grades", catalog = "student_database")

// Grades method 
public class Grades implements java.io.Serializable {
	// intializing variables
	private int idgrades;
	private String gradesDistribution;
	private int requiredMarks;

	// constructor
	public Grades() {
	}
	// initializes the variable 
	public Grades(int idgrades, String gradesDistribution, int requiredMarks) {
		this.idgrades = idgrades;
		this.gradesDistribution = gradesDistribution;
		this.requiredMarks = requiredMarks;
	}

	// gets grades id
	@Id
	@Column(name = "idgrades", unique = true, nullable = false)
	public int getIdgrades() {
		return this.idgrades;
	}

	// sets grades id
	public void setIdgrades(int idgrades) {
		this.idgrades = idgrades;
	}

	// gets grades distribution 
	@Column(name = "Grades_Distribution", nullable = false, length = 45)
	public String getGradesDistribution() {
		return this.gradesDistribution;
	}
	
	// sets grade distribution
	public void setGradesDistribution(String gradesDistribution) {
		this.gradesDistribution = gradesDistribution;
	}

	// gets required marks
	@Column(name = "Required_Marks", nullable = false)
	public int getRequiredMarks() {
		return this.requiredMarks;
	}

	// sets required marks
	public void setRequiredMarks(int requiredMarks) {
		this.requiredMarks = requiredMarks;
	}

}
