// package name
package com.student.project;
// Generated Mar 25, 2016 2:00:16 AM by Hibernate Tools 4.3.1.Final

// importing hibernate utilities
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Library generated by hbm2java
 */

// Library method
@SuppressWarnings("serial")
@Entity
@Table(name = "library", catalog = "student_database")
public class Library implements java.io.Serializable {
	// variable declarations
	private int idlibrary;
	private String books;
	private int returnDays;
	private String major;

	// Constructor
	public Library() {
	}

	// initializes the values
	public Library(int idlibrary, String books, int returnDays, String major) {
		this.idlibrary = idlibrary;
		this.books = books;
		this.returnDays = returnDays;
		this.major = major;
	}

	// gets library id
	@Id
	@Column(name = "idlibrary", unique = true, nullable = false)
	public int getIdlibrary() {
		return this.idlibrary;
	}

	// sets library id
	public void setIdlibrary(int idlibrary) {
		this.idlibrary = idlibrary;
	}

	// gets book name
	@Column(name = "Books", nullable = false, length = 45)
	public String getBooks() {
		return this.books;
	}

	// sets book name
	public void setBooks(String books) {
		this.books = books;
	}
	
	// gets return days
	@Column(name = "Return_Days", nullable = false)
	public int getReturnDays() {
		return this.returnDays;
	}

	// sets return days
	public void setReturnDays(int returnDays) {
		this.returnDays = returnDays;
	}

	// gets major
	@Column(name = "Major", nullable = false, length = 45)
	public String getMajor() {
		return this.major;
	}

	// sets major
	public void setMajor(String major) {
		this.major = major;
	}
}
