package com.student.project;
// Generated Mar 25, 2016 2:00:16 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Student generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "student", catalog = "student_database")
public class Student implements java.io.Serializable {

	private int idstudent;
	private String firstName;
	private String lastName;
	private int age;
	private String major;

	public Student() {
	}

	public Student(int idstudent, String firstName, String lastName, int age, String major) {
		this.idstudent = idstudent;
		this.firstName = firstName;
		this.lastName = lastName;
		this.age = age;
		this.major = major;
	}

	@Id

	@Column(name = "idstudent", unique = true, nullable = false)
	public int getIdstudent() {
		return this.idstudent;
	}

	public void setIdstudent(int idstudent) {
		this.idstudent = idstudent;
	}

	@Column(name = "First_Name", nullable = false, length = 45)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "Last_Name", nullable = false, length = 45)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "Age", nullable = false)
	public int getAge() {
		return this.age;
	}

	public void setAge(int age) {
		this.age = age;
	}

	@Column(name = "Major", nullable = false, length = 45)
	public String getMajor() {
		return this.major;
	}

	public void setMajor(String major) {
		this.major = major;
	}

}
